# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Maps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Maps
  pod 'GoogleMaps'
  target 'MapsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapsUITests' do
    # Pods for testing
  end

end
